# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🎼 Music activity and suggestions - Apple Music - Random track from playlist
        uses: lowlighter/metrics@master
        with:
          filename: metrics/metrics.plugin.music.playlist.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_playlist: https://embed.music.apple.com/fr/playlist/usr-share/pl.u-V9D7m8Etjmjd0D
          plugin_music_limit: 2
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🎼 Music activity and suggestions - Spotify - Random track from playlist
        uses: lowlighter/metrics@master
        with:
          filename: metrics/metrics.plugin.music.playlist.spotify.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_playlist: https://open.spotify.com/embed/playlist/3nfA87oeJw4LFVcUDjRcqi
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🎼 Music activity and suggestions - Spotify - Recently listed
        uses: lowlighter/metrics@master
        with:
          filename: metrics/metrics.plugin.music.recent.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 2
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🎼 Music activity and suggestions - Spotify - Top tracks
        uses: lowlighter/metrics@master
        with:
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🎼 Music activity and suggestions - Spotify - Top artists
        uses: lowlighter/metrics@master
        with:
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: long
          plugin_music_top_type: artists
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🗼 Rss feed - News from hackernews
        uses: lowlighter/metrics@master
        with:
          filename: metrics/metrics.plugin.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🗳️ Leetcode - LeetCode
        uses: lowlighter/metrics@master
        with:
          filename: metrics/metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🥠 Fortune - Fortune
        uses: lowlighter/metrics@master
        with:
          filename: metrics/metrics.plugin.fortune.svg
          token: NOT_NEEDED
          base: ""
          plugin_fortune: yes
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 📗 Classic template - Example
        uses: lowlighter/metrics@master
        with:
          filename: metrics/metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 📘 Repository template - Example
        uses: lowlighter/metrics@master
        with:
          template: repository
          filename: metrics/metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          user: Jesse-0x
          repo: metrics
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          output_action: none
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 📙 Terminal template - Example
        uses: lowlighter/metrics@master
        with:
          template: terminal
          filename: metrics/metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
          output_action: none
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 📒 Markdown template - Example
        uses: lowlighter/metrics@master
        with:
          template: markdown
          filename: metrics/metrics.markdown.md
          markdown: >-
            https://raw.githubusercontent.com/lowlighter/metrics/examples/metrics.markdown.template.md
          config_output: markdown
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: examples
          user: Jesse-0x
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
